%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}, 'fontFamily': 'Montserrat', 'fontSize': 10}}%%

        %% GenPipes Diagram for monitor.sh working
        %% Ref: https://bitbucket.org/mugqic/genpipes/src/master/utils/monitor.sh
        %% Author Shaloo Shalini <shalz@hotmail.com>

        graph TD
          InputBW[[fa:fa-file-archive-o Pipeline Command]]:::inputfill
          Node1{{ 1. <br/> -g PipelineScript.sh }}:::nodefill
          Node2{{ 2. <br/> chunk_genpipes.sh utility }}
          Node2out{{ Job Chunks Folder }}:::inputfill
          Node3{{ 3. <br/> monitor.sh utility }}:::nodefill
          Node4{{ 4. <br/>Watch command }}:::nodefill
          Scheduler([fa:fa-sticky-note-o Scheduler ])

          InputBW --> Node1
          Node1 -.-> Node2 -.-> Node2out -.-> Node3 
          Node3 -. Smartly submit <br/> chunked jobs .-> Scheduler
          Node3 -. Monitor <br/> job chunk <br/> folder .-> Node2out
          Node4 -.-> Scheduler
 
          subgraph pipeline[" "]
            Node1
          end

          subgraph chunk[" "]
            Node2
            Node2out
          end

           subgraph monitorutil[" "]
            Node3
          end
          
           subgraph monitor[" "]
            Node4
          end

          classDef inputfill fill:#ffffff,stroke:gray,stroke-width:1px
          classDef nodefill fill:#ffffff,stroke:black,stroke-width:1px
          classDef whiterect fill:#eaeaea,stroke:#eaeaea
          classDef yellowrect fill:#f8d354,stroke:#ffffff
          classDef creamrect fill:#fef8ec, stroke:#ffffff
          classDef lightgrect fill:#aaaaaa, stroke:#f0f0f0

          class InputBW inputfill
          class pipeline whiterect
          class chunk yellowrect
          class monitor creamrect
          class monitorutil lightgrect

