  - **Old Format** 

    .. parsed-literal::
    
        user@\ |key_ccdb_server_cmd_name|\ % <pipeline name>.py [options] -g genpipes_cmd.sh
        user@\ |key_ccdb_server_cmd_name|\ % bash genpipes_cmd.sh

  - **New Format** 
  
    .. parsed-literal::

        user@\ |key_ccdb_server_cmd_name|\ % genpipes <pipeline name> [options] -g genpipes_cmd.sh
        user@\ |key_ccdb_server_cmd_name|\ % bash genpipes_cmd.sh