.. tab-set:: 

      .. tab-item:: 6.x

         
         See Genpipes `GitHub repository changelog <https://github.com/c3g/GenPipes/blob/main/CHANGELOG.md>`_.

      .. tab-item:: v5.x or lower

         See Bitbucket repository for the GenPipes `ChangeLog <https://bitbucket.org/mugqic/genpipes/src/master/CHANGELOG.md>`_.       

Since we use git, there are many ways to get the details in many formats.
One of our preferred ways is to use a `script <https://raw.github.com/sebhtml/ray/master/scripts/dump-ChangeLog.sh>`_ that lists the commits by tag and author, written by the author of the Ray assembler: Sébastien Boisvert. 

.. dropdown:: :material-outlined:`mail;2em`  Feedback 
   :color: info
   :open:
   
   *Are you enjoying Genpipes?*

   We'd love to :ref:`hear your inputs, feedback<docs_how_to_get_support>`, if any!
