.. _docs_gp_changelog:

Where is the detailed ChangeLog?
---------------------------------

A `ChangeLog (CHANGELOG.md) <https://bitbucket.org/mugqic/genpipes/src/master/CHANGELOG.md>`_ is available in the repository.

Since we use git, there are many ways to get the details in many formats.
One of our preferred ways is to use a script written by the author of the Ray assembler: Sébastien Boisvert, which lists the commits by tag and author:

https://raw.github.com/sebhtml/ray/master/scripts/dump-ChangeLog.sh

Enjoy GenPipes!  We'd love to hear your feedback and inputs!
