%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}}}%%

        %% GenPipes Schema for longread_dnaseq.py
        %% Ref: https://github.com/c3g/GenPipes/tree/main/genpipes/pipelines/longread_dnaseq
        %% Author Shaloo Shalini <shalz@hotmail.com>

        graph LR
          Node1{{ 1.<br/> BlastQC }}:::nodefill
          Node2{{ 2.<br/> Metrics Nanoplot}}:::nodefill
          Node3{{ 3.<br/> Minimap2 <br/> Align }}:::nodefill
          Node4{{ 4.<br/> PycoQC }}:::nodefill
          Node5{{ 5.<br/> SAMtools Merge <br/> BAM Files }}:::nodefillblack
          Node6{{ 6.<br/> Metrics <br/> Nanoplot Aligned }}:::nodefill
          Node7{{ 7.<br/> Metrics <br/> Mosdepth }}:::nodefill
          Node8{{ 8.<br/> Set <br/> Variant Calling <br/> Regions }}:::nodefill
          Node9{{ 9.<br/> Clair3 }}:::nodefill
          Node10{{ 10.<br/> Merge Filter <br/> Clair3 }}:::nodefill
          Node11{{ 11.<br/> Whatshap }}:::nodefill
          Node12{{ 12.<br/> QDNAseq }}:::nodefill
          Node13{{ 13.<br/> Dysgu }}:::nodefill
          Node14{{ 14.<br/> SVIM }}:::nodefill
          Node15{{ 15.<br/> MultiQC }}:::nodefill
          Node16{{ 16.<br/> Modkit }}:::nodefill
          Output([fa:fa-sticky-note-o Report ])

          Input1[[fa:fa-file-archive-o .BAM]] --> Node1 -.-> Node2
          Input2[[fa:fa-file-archive-o .FASTQ]] --> Node2
          Node2 -.-> Node3 -.-> Node5
          Node5 -.-> Node6 & Node7 & Node8 & Node9 & Node11 & Node12 & Node14 & Node16
          Node8 -.-> Node9 -.-> Node10 -.-> Node11 -.-> Node13
          Node2 & Node6 & Node7 -.-> Node15

          Output([fa:fa-sticky-note-o Report ])
          Node16 ---> Output
          subgraph readSetSteps[" "]
            Node1
            Node2
            Node3
            Node4
          end
          Node5
          subgraph sampleSetSteps[" "]
            Node6
            Node7
            Node8
            Node9
            Node10
            Node11
            Node12
            Node13
            Node14
            Node15
            Node16
            Output
          end
          classDef greenRect fill:#E4FBF4,stroke:white
          class readSetSteps greenRect
          classDef blueRect fill:#DEF6FC,stroke:white
          class sampleSetSteps blueRect
          classDef nodefill fill:#ffffff,stroke:gray,stroke-width:2px
          classDef nodefillblack fill:black,stroke:black,color:white,stroke-width:2px
