``ampliconseq``

.. include:: /common/commands/ampliconseq.inc

``chipseq``

.. include:: /common/commands/chipseq.inc

``covseq``

.. include:: /common/commands/covseq.inc

``nanopore covseq``

.. include:: /common/commands/nanopore_covseq.inc

``rnaseq``

.. include:: /common/commands/rnaseq.inc

``dnaseq``

.. tab-set:: 

    .. tab-item:: Germline HighCov

        .. include:: /common/commands/dnaseq_germ_hc.inc

    .. tab-item:: Germline SNV

        .. include:: /common/commands/dnaseq_germ_snv.inc

    .. tab-item:: GermlineSV

        .. include:: /common/commands/dnaseq_germ_sv.inc

.. tab-set:: 

    .. tab-item:: Somatic Ensemble 

        .. include:: /common/commands/dnaseq_so_ensemble.inc

    .. tab-item:: Somatic Fastpass

        .. include:: /common/commands/dnaseq_so_fastpass.inc

    .. tab-item:: Somatic SV 

        .. include:: /common/commands/dnaseq_so_sv.inc

    .. tab-item:: Somatic Tumor

        .. include:: /common/commands/dnaseq_so_tumor.inc

``rnaseq_light``

.. include:: /common/commands/rnaseq_light.inc

``rnaseq_denovo_assembly``

.. include:: /common/commands/rnaseq_denovo.inc

``methylseq``

.. include:: /common/commands/methylseq.inc

``longread``

.. tab-set:: 

    .. tab-item:: Nanopore

        .. include:: /common/commands/lr_dna_nanopore.inc

    .. tab-item:: Revio

        .. include:: /common/commands/lr_dna_revio.inc

.. include:: /common/gp_cluster_ini.inc
