.. admonition:: Using GenPipes on DRAC Servers
   :class: danger

   You may need to `enable access to the latest DRAC servers <https://ccdb.alliancecan.ca/me/access_systems>`_ to use GenPipes.

   If you are using GenPipes |genpipes_version| on any of the
   following DRAC servers, please note that these servers are
   **not available** anymore:

   * Beluga
   * Cedar
   * Graham
   * Niagara

   For the time being, you can run the GenPipes pre-deployed on **Narval**. Use `narval.ini`
   when running these pipelines.

   In the future, a newer release of GenPipes will enable <server>.ini files
   and enable you to use the new DRAC servers:

   * Rorqual
   * Fir
   * Nibi   
   * Trillium