::

  -t {bismark, dragen, hybrid}, --type {bismark, dragen, hybrid}

                            Methylseq analysis type.
                            
.. warning::

     For most users, only the `bismark` protocol (default) is applicable. The `dragen` and `hybrid` protocols require the use of the proprietary `Illumina Dragen Bio-IT platform <https://sapac.illumina.com/products/by-type/informatics-products/dragen-bio-it-platform.html>`_, which is not available on the Compute Canada clusters and requires an active license on the Abacus cluster.
