::

  -t {germline_snv, germline_sv, germline_high_cov, somatic_tumor_only, somatic_fastpass, somatic_ensemble, somatic_sv},
 
  --type {germline_snv, germline_sv, germline_high_cov, somatic_tumor_only, somatic_fastpass, somatic_ensemble, somatic_sv}

                            DNAseq analysis type (default=germline_snv)

::

  -p PAIRS, --pairs PAIRS 

                            pairs file
                            format - patient_name,normal_sample_name,tumor_sample_name