For most users, only the default `bismark` protocol and the `gembs` protocol are applicable. 
     
The `dragen` and `hybrid` protocols require the use of the proprietary `Illumina Dragen Bio-IT platform <https://sapac.illumina.com/products/by-type/informatics-products/dragen-bio-it-platform.html>`_. This software is not available if you are using GenPipes deployed on the `Digital Research Alliance of Canada (DRAC) <https://alliancecan.ca/en>`_, formerly Compute Canada, clusters. It requires an active license on the Abacus cluster.
