.. _docs_steps_dnaseq:

Step Details
-------------

Following are the various steps that are part of GenPipes DNA Sequencing genomic analysis pipeline:

.. _Picard SAM to FastQ:

**Picard SAM to FastQ**

TBD

.. _Sym Link FastQ:

**Sym Link FastQ**

TBD

.. _Trimmomatic:

**Trimmomatic**

TBD

.. _Merge Trimmomatic Stats:

**Merge Trimmomatic Stats**

TBD

.. _Skewer Trimming:

** Skewer Trimming**

TBD

.. _BWA Picard Sort SAM:

**BWA Picard Sort SAM**

TBD

.. _SAMBAM Merge SAM Files:

**SAMBAM Merge SAM Files**

TBD

.. _GATK Indel Re-aligner:

**GATK Indel Re-aligner**

TBD

.. _SAMBAM Merge Realigned:

**SAMBAM Merge Realigned**

TBD

.. _Fix Mate by Coordinate:

**Fix Mate by Coordinate**

TBD

.. _Picard Mark Duplicates:

**Picard Mark Duplicates**

TBD

.. _Recalibration:

**Recalibration**

TBD

.. _Sym Link Final BAM:

**Sym Link Final BAM**

.. _Metrics DNA Picard:

**Metrics DNA Picard**

.. _Metrics DNA Sample Quality Map:

**Metrics DNA Sample Quality Map**

.. _Metrics DNA SAMBAM Flag Stats:

**Metrics DNA SAMBAM Flag Stats**

.. _Metrics DNA FastQC:

**Metrics DNA FastQC**

.. _Picard Calculate HS Metrics:

**Picard Calculate HS Metrics**

.. _GATK Callable Loci:

**GATK Callable Loci**

.. _Extract Common SNP Frequencies:

**Extract Common SNP Frequencies**

.. _BAF Plot:

**BAF Plot**

.. _GATK Haplotype Caller:

**GATK Haplotype Caller**

.. _Merge and call individual GVCF:

**Merge and call individual GVCF**

.. _Combine GVCF:

**Combine GVCF**

.. _Merge and call combined GVCF:

**Merge and call combined GVCF**

.. _Variant Recalibrator:

**Variant Recalibrator**

.. _Haplotype caller decompose and normalize:

**Haplotype caller decompose and normalize**

.. _Haplotype caller flag mappability:

**Haplotype caller flag mappability**

.. _Haplotype caller SNP ID annotation:

**Haplotype caller SNP ID annotation**

.. _Haplotype caller SNP Effect:

**Haplotype caller SNP Effect**

.. _Haplotype caller dbNSFP annotation:

**Haplotype caller dbNSFP annotation**

.. _Haplotype caller Gemini annotation:

**Haplotype caller Gemini annotation**

.. _Haplotype caller metrics VCF stats:

**Haplotype caller metrics VCF stats**

.. _Run MultiQC:

**Run MultiQC**

.. _Raw MPileup:

**Raw MPileup**

.. _Compress Raw MPileup:

**Compress Raw MPileup**

.. _SNP and indel BCF:

**SNP and indel BCF**

.. _Merge Filter BCF:

**Merge Filter BCF**

.. _MPileup decompose and normalize:

**MPileup decompose and normalize**

.. _MPileup Flag Mappability:

**MPileup Flag Mappability**

.. _Mpileup SNP ID annotation:

**Mpileup SNP ID annotation**

.. _MPileup SNP Effect:

**MPileup SNP Effect**

.. _MPileup dbNSFP annotation:

**MPileup dbNSFP annotation**

.. _MPileup Gemini annotation:

**MPileup Gemini annotation**

.. _MPileup Metrics VCF stats:

**MPileup Metrics VCF stats**
Use link like this `Linksample`_.

.. Following are the html link references:

.. _Linksample: http://www.hpc.mcgill.ca/index.php/training#past_workshops
