.. _docs_steps_rnaseq:

.. spelling:: 


Step Details
-------------

.. _Picard SAM to FastQ:

**Picard SAM to FastQ**

TBD

.. _Trimmomatic:

**Trimmomatic**

.. _Merge Trimmomatic Stats:

**Merge Trimmomatic Stats**

.. _Star Processing:

**Star Processing**

.. _Picard Merge SAM Files:

**Picard Merge SAM Files**

TBD

.. _Picard Sort SAM:

**Picard Sort SAM**

TBD

.. _Picard Mark Duplicates:

**Picard Mark Duplicates**

TBD

.. _Picard RNA Metrics:

**Picard RNA Metrics**

TBD

.. _Estimate Ribosomal RNA:

**Estimate Ribosomal RNA**

TBD

.. _BAM Hard Clip:

**BAM Hard Clip**

TBD

.. _RNA Seq Compress:

**RNA Seq Compress**

TBD

.. _Wiggle:

**Wiggle**

TBD

.. _Raw Counts:

**Raw Counts**

TBD

.. _Raw Counts Metrics:

**Raw Counts Metrics**

TBD

.. _Cufflinks Process:

**Cufflinks Process**

TBD

.. _Cuffmerge Process:

**Cuffmerge Process**

TBD

.. _Cuffquant Step:

**Cuffquant Step**

TBD

.. _Cuffdiff Process:

**Cuffdiff Process**

TBD

.. _Cuffnorm Normalization:

**Cuffnorm Normalization**

TBD

.. _FPKM Correlation:

**FPKM Correlation**

TBD

.. _GQ RNA Sequencing Utility:

**GQ RNA Sequencing Utility**

TBD

.. _Differential Expression:

**Differential Expression**

TBD

.. _Differential Expression GO sequencing:

**Differential Expression GO sequencing**

TBD

.. _IHEC Metrics:

**IHEC Metrics**

TBD

.. _Verify BAM ID:

**Verify BAM ID**

TBD

.. _Stringtie:

**Stringtie**

TBD

.. _Stringtie Assemble Transcriptome:

**Stringtie Assemble Transcriptome**

TBD

.. _Stringtie Merge:

**Stringtie Merge**

TBD

.. _Ballgown Gene Expression:

**Ballgown Gene Expression**

TBD 
