# This is a basic workflow to help you get started with Actions

name: GenPipes Check 

on: [push]
jobs:
   job1:
    name: unit testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
          docs-folder: "docs/"
