# This is a basic workflow to help you get started with Actions

name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y enchant git && pip3 install sphinx sphinx_rtd_theme"  
        build-command: 'make spelling BUILDDIR=${{ github.workspace }}/build'
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v2
      with:
        name: spell-log
        path: ${{ github.workspace }}/build/spelling/output.txt

  displaylog:
    name: show spelling log
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: spell-log
      - shell: bash
        run: |
          value=`cat ${{ github.workspace }}/build/spelling/output.txt`
          echo The Spelling Output is $value
