# This is a basic workflow to help you get started with Actions

name: Spell Check 
on: [push]
jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
          brew update
          brew install enchant
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          pip install -r docs/requirements.txt
    - name: Sphinx build
      run: |
          val=`ls -alth`
          echo This is current dir contents $val
          make -C docs/ clean html spelling >buildlog.txt
    - name: Check dir contents
      run: | 
          val2=`ls -alth`
          echo This is current dir contents $val2
    - name: Upload artifacts 
    - uses: actions/upload-artifact@v2
      with:
          name: buildlogfile
          path: buildlog.txt

  show_log:
    needs: macos_build
    runs-on: macos_latest
    steps:
    - name: Show the Log
      uses: actions/download-artifact@v2
      with:
          name: buildlogfile
    - shell: bash
      run: | 
          value=`cat buildlog.txt`
          echo The OUTPUT of spelling check is ......
          echo $value
