# This is a basic workflow to help you get started with Actions

name: Spell Check 
on: [push]
jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
          brew update
          brew install enchant
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          pip install -r docs/requirements.txt
          make -C docs/ spelling > ${{ github.workspace }}/spell-log.txt
    - uses: actions/upload-artifact@v2
      with:
          name: spellinglogfile
          path: ${{ github.workspace }}/spell-log.txt

  show_log:
    needs: macos_build
    runs-on: macos_latest
    steps:
    - uses: actions/download-artifact@v2
      with:
          name: spellinglogfile
    - shell: bash
      run: | 
          value=`cat ${{ github.workspace }}/spell-log.txt`
          echo The OUTPUT of spelling check is ......
          echo $value
