# This is a basic workflow to help you get started with Actions

name: linuxosbuild
on: [pull_request]
jobs:
  ubuntu_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: '3.13'
    - name: linux build dependencies
      run: |
#         export SETUPTOOLS_USE_DISTUTILS=stdlib
          sudo apt-get update -y && sudo apt-get install -y build-essential make libenchant-dev enchant git dialog apt-utils && sudo apt-get autoremove && sudo apt-get clean
          python3 -m pip install --upgrade pip
          python3 -m pip install -U sphinx==8.1.3
          python3 -m pip install --upgrade setuptools wheel
          python3 -m pip install -r docs/requirements.txt
    - name: Sphinx Build
      run:  |
           make -C docs spelling html
