# This is a basic workflow to help you get started with Actions

name: linuxosbuild
on: [pull_request]
jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: linux build dependencies
      run: |
          export SETUPTOOLS_USE_DISTUTILS=stdlib
          sudo apt-get update -y && sudo apt-get install -y build-essential make libenchant-dev enchant git dialog apt-utils && sudo apt-get autoremove && sudo apt-get clean
          python3 -m pip install --upgrade setuptools
          python3 -m pip install -r docs/requirements.txt
    - name: Sphinx Build
      run:  |
           make -C docs spelling html
