# This is a basic workflow to help you get started with Actions

name: CI
on: [push, pull_request]
jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
          brew update
          brew install enchant
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          pip install -r docs/requirements.txt
          make -C docs/ spelling
          cat build/spelling/output.txt
