# This is a basic workflow to help you get started with Actions

name: linuxosbuild
on: [push]
jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.12'
    - name: linux build dependencies
      run: |
          export SETUPTOOLS_USE_DISTUTILS=stdlib
          sudo apt-get update -y && sudo apt-get install -y build-essential make libenchant-dev enchant git dialog apt-utils && sudo apt-get autoremove && sudo apt-get clean
          python3 -m pip install --upgrade setuptools
          python3 -m pip install -r docs/requirements.txt
    - name: Sphinx Build
      run:  |
           make -C docs spelling html

#name: macosbuild 
#on: [push]
#jobs:
#  macos_build:
#    runs-on: macos-latest
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: 3.11.4
#    - name: Install Dependencies
#      run: |
#          brew update
#          brew upgrade
#          brew install enchant
#          brew install mermaid-cli
#          python3 -m pip3 install --upgrade pip3
#          pip3 install -r docs/requirements.txt
#    - name: Sphinx build
#      run: |
#          val=`ls -alth`
#          echo This is current dir contents $val
#          make -C docs/ clean spelling html 
