# This is a basic workflow to help you get started with Actions

name: macosbuild 
on: [push]
jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13.0
    - name: Install Dependencies
      run: |
          brew update
          brew upgrade
          brew install enchant
          brew list enchant
          ls $(brew --prefix enchant)
          export PYENCHANT_LIBRARY_PATH=$(brew --prefix enchant)/lib/libenchant-2.2.dylib
          export DYLD_LIBRARY_PATH=/opt/homebrew/lib/:$(brew --prefix enchant)/lib/
          python -m pip install --upgrade pip
          pip install enchant
          pip install -r docs/requirements.txt
    - name: Sphinx build
      run: |
          val=`ls -alth`
          echo This is current dir contents $val
          make -C docs/ clean html spelling
