# This is a basic workflow to help you get started with Actions

name: linuxosbuild
on: [pull_request]
jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y enchant git && pip3 install sphinx sphinx-rtd-theme && && pip3 install -r docs/requirements.txt"  
        build-command: 'make spelling html'
        docs-folder: "docs/"
